#!/bin/sh
# File generated by ocamlbuild

cd '/home/muhammad/workspace_ocaml/CS 3110 PS6'

rm -f steammon/game/game.cmi
rm -f steammon/game/netgraphics.cmi
rm -f steammon/game/netgraphics.cmo
rm -f steammon/game/server.cmi
rm -f steammon/game/server.cmo
rm -f steammon/shared/connection.cmi
rm -f steammon/shared/connection.cmo
rm -f steammon/shared/constants.cmi
rm -f steammon/shared/constants.cmo
rm -f steammon/shared/definitions.cmi
rm -f steammon/shared/definitions.cmo
rm -f steammon/shared/thread_pool.cmi
rm -f steammon/shared/thread_pool.cmo
rm -f steammon/shared/util.cmi
rm -f steammon/shared/util.cmo
rm -f steammon/team/babybot.cmi
rm -f steammon/team/babybot.cmo
rm -f steammon/team/team.cmi
rm -f steammon/team/team.cmo
# Also clean the script itself
rm -f '/home/muhammad/workspace_ocaml/CS 3110 PS6/_build/sanitize.sh'
